### ISSUE TITLE
Při spuštění není vybraný segment (room)

### ISSUE THREAD

**Issue by ondra-marik** [NanookCZ/csvToFirebase-PyConMobileApp#2]
![img_0034](https://cloud.githubusercontent.com/assets/11720224/20560364/3dc432ae-b179-11e6-905d-8d95c86eae42.PNG)

iOS 10.1.1

**Comment by SvetlanaM** [comment]
no ja som to práve zvažovala či to zakliknem preddefinovane ale nie, treba to? nemôže byť to prvé spustenie ako defaultné dáta a potom sa preklikáva už ďalej?

**Comment by ondra-marik** [comment]
pokud by byla data nezávislá na místnosti pak ano, ale ten program se vztahuje k místnosti ne? Nebo jsem se přehlédl a je tam kompletní program?

**Comment by SvetlanaM** [comment]
ee nie je, no tak to zaskrtnem prve ako defaultne
