### ISSUE TITLE
Chybová hláška po zamknutí telefonu

### ISSUE THREAD

**Issue by ondra-marik** [NanookCZ/csvToFirebase-PyConMobileApp#3]
![img_0035](https://cloud.githubusercontent.com/assets/11720224/20560433/a25e849e-b179-11e6-80aa-fa10819add6e.PNG)

iOS 10.1.1 (na wifi)

1. Spustit appku
2. Zamknout telefon (appka může být i na pozadí, nastaven kód/touch id)
3. Odemknout telefon a případně otevřít appku

**Comment by SvetlanaM** [comment]
no toto nezmením :D iba ak prestanem používať firebase :D alebo minimálne firebase offline režim, táto hláška sa ukáže, keď si firebase myslí, že je sieť offline a to je skôr ako mu príde nejaký token do toho plistu
