### ISSUE TITLE
Twitter barva navigation baru 

### ISSUE THREAD

**Issue by ondra-marik** [NanookCZ/csvToFirebase-PyConMobileApp#4]
Nejsem si ani jistý, jestli jde změnit nějak pokud je to framework a možná se ani nehodí, jen by možná vypadalo lépe se stejnou barvou jako zbytek appky (nebo alespoň černý status bar).

![img_0036](https://cloud.githubusercontent.com/assets/11720224/20569198/887a43d0-b19f-11e6-9afe-9bdcb56626c1.PNG)

**Comment by SvetlanaM** [comment]
k tomuto kodu nemam pristup, je to v tom fabricu priamo, ja viem iba tu obrazovku predtym upravit, uz som to googlila
